### ISSUE TITLE
各行政機関のCOVID-19関係の制度（追加案）

### ISSUE THREAD

**Issue by Yasuaki-Yamazaki** [matsuihidetoshi/covid19support#1]
特別定額給付金（仮称）
https://www.soumu.go.jp/menu_seisaku/gyoumukanri_sonota/covid-19/kyufukin.html

小規模事業者持続化補助金に関する売上減少の証明
https://www.city.hamamatsu.shizuoka.jp/sangyosomu/sangyosomu/jizokukahojokinn.html

セーフティネット保証制度4号の認定
https://www.city.hamamatsu.shizuoka.jp/sangyosomu/sangyosomu/4gou.html

セーフティネット保証制度5号の認定
https://www.city.hamamatsu.shizuoka.jp/sangyosomu/sangyosomu/5gou.html

雇用調整助成金（従業員の休業手当）
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/kyufukin/pageL07.html

雇用調整金助成金の解説動画
https://www.rodo.co.jp/sr/571668/

**Comment by matsuihidetoshi** [comment]
- 小規模事業者持続化補助金に関する売上減少の証明  
こちらは追記済みでした。

- 雇用調整金助成金の解説動画  
こちらは行政機関のサイトではないため、公平性にかけると判断し見送りました。
